version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm run lint:ci
      - run: npm run test
      - run: cd test-results && mkdir junit && cd ..
      - run: mv js-lint-results.xml test-results/junit/

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  sonar:
    docker:
      - image: sonar:sonar

    working_directory: ~/repo
    steps:
      - run: mvn sonar:sonar -Dsonar.organization=rthewhite-github  \
                                          -Dsonar.projectKey=rthewhite_mini-transactor \
                                          -Dsonar.sources=. \
                                          -Dsonar.host.url=https://sonarcloud.io \
                                          -Dsonar.login=5ca007708bf69e0910ba6d1d73aa4027b378fd45

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sonar

